import type { Product } from "../lib/types"

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Hibiscus Roots Infusions",
    description: "Loose Tea",
    customerPrice: 80,
    retailPrice: 60,
    wholesalePrice: 45,
    image: "/hr.png",
  },
  {
    id: "2",
    name: "Hibiscus Ginger",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hg.png",
  },
  {
    id: "3",
    name: "Hibiscus Ginger Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hgt.png",
  },
  {
    id: "4",
    name: "Hibiscus Cinnamon",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hc.png",
  },
  {
    id: "5",
    name: "Hibiscus Cinnamon Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hct.png",
  },
  {
    id: "6",
    name: "Hibiscus Senna",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hs.png",
  },
  {
    id: "7",
    name: "Hibiscus Senna Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hst.png",
  },
  {
    id: "8",
    name: "Hibiscus Prekese",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hpr.png",
  },
  {
    id: "9",
    name: "Hibiscus Prekese Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hprt.png",
  },
  {
    id: "10",
    name: "Hibiscus Orange",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/ho.png",
  },
  {
    id: "11",
    name: "Hibiscus Orange Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hot.png",
  },
  {
    id: "12",
    name: "Hibiscus Pineapple",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hpi.png",
  },
  {
    id: "13",
    name: "Hibiscus Pineapple Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hpit.png",
  },
  {
    id: "14",
    name: "Hibiscus Moringa",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hmo.png",
  },
  {
    id: "15",
    name: "Hibiscus Moringa Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hmot.png",
  },
  {
    id: "16",
    name: "Hibiscus Mint",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hmi.png",
  },
  {
    id: "17",
    name: "Hibiscus Mint Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hmit.png",
  },
  {
    id: "18",
    name: "Hibiscus Lemon Grass",
    description: "Tea Bags, 52g (15 Tea Bags)",
    customerPrice: 50.00,
    retailPrice: 40.00,
    wholesalePrice: 30.00,
    image: "/hl.png",
  },
  {
    id: "19",
    name: "Hibiscus Lemon Grass Tin",
    description: "Tea Bags, 130g (25 Tea Bags)",
    customerPrice: 100.00,
    retailPrice: 80.00,
    wholesalePrice: 60.00,
    image: "/hlt.png",
  },
]
